/**
 * @module tests/test-review-comment
 * @description ENT-004 (audit) — regression coverage for the
 * `tests.reviewComment` column added by migration 054.
 *
 * What this pins:
 *   1. `testRepo.update({ reviewComment })` actually persists the column.
 *      Pre-migration 054 this was silently dropped by `VALID_COLS`
 *      filtering — Lifeguard flagged the bug at PR review time. The test
 *      below is the canonical regression: if the column ever gets
 *      removed from `INSERT_COLS` again, this assertion fires.
 *   2. The column round-trips correctly via `rowToTest()` — no JSON
 *      parsing weirdness even though `tests` has other JSON columns.
 *   3. `bulkUpdateReviewStatus({ extraFields: { reviewComment } })` also
 *      persists the field (this is the path a future "reject with
 *      comment" UI would use).
 *   4. NULL is the default for pre-migration rows AND for any update
 *      that doesn't touch the column — touching `reviewStatus` without
 *      a comment must not blow away an existing comment.
 *   5. Clearing the column (writing `null`) works — the restore /
 *      revoke paths need this so a re-approved test doesn't keep the
 *      stale auto-regeneration comment from a prior cycle.
 *
 * Usage: node backend/tests/test-review-comment.test.js
 */

import assert from "node:assert/strict";
import { resetDb } from "./helpers/test-base.js";
import * as testRepo from "../src/database/repositories/testRepo.js";
import * as projectRepo from "../src/database/repositories/projectRepo.js";

let projectCounter = 0;
let testCounter = 0;

function makeProject() {
  const project = {
    id: `PRJ-${++projectCounter}`,
    name: "Proj",
    url: "https://example.com",
    workspaceId: null, // FK skipped for unit-test scope (see auto-approval.test.js)
    createdAt: new Date().toISOString(),
  };
  projectRepo.create(project);
  return project;
}

function makeTest(projectId, overrides = {}) {
  const id = `TST-${++testCounter}`;
  const test = {
    id,
    projectId,
    name: "Test",
    description: "",
    steps: [],
    playwrightCode: null,
    priority: "medium",
    type: "manual",
    sourceUrl: "https://example.com",
    pageTitle: "",
    createdAt: new Date().toISOString(),
    reviewStatus: "draft",
    workspaceId: null,
    ...overrides,
  };
  testRepo.create(test);
  return id;
}

async function main() {
  resetDb();

  // ── 1. Round-trip via testRepo.update ────────────────────────────────────
  // The original Lifeguard bug: `testRepo.update({ reviewComment: "…" })`
  // was a no-op because the column wasn't in INSERT_COLS / VALID_COLS.
  // A passing assertion here proves the migration + repo update landed.
  {
    const project = makeProject();
    const testId = makeTest(project.id);
    const reviewComment = "Auto-regenerated by feedback loop after failure (SELECTOR_ISSUE). Original code preserved in run results.";

    testRepo.update(testId, { reviewComment });
    const saved = testRepo.getById(testId);
    assert.equal(
      saved.reviewComment,
      reviewComment,
      "reviewComment must round-trip — if this fails, the column is being dropped by VALID_COLS",
    );
  }

  // ── 2. Column round-trips via rowToTest without JSON parsing ─────────────
  // The `tests` table has several JSON columns (`steps`, `tags`,
  // `qualityScoreFactors`). `reviewComment` is plain TEXT — it must not
  // accidentally get parsed as JSON by `rowToTest`. Test with a string
  // that happens to look JSON-ish to catch any drift.
  {
    const project = makeProject();
    const testId = makeTest(project.id);
    const trickyComment = `Reason: {"category": "BOT_BLOCK"} — see /sorry/index`;

    testRepo.update(testId, { reviewComment: trickyComment });
    const saved = testRepo.getById(testId);
    assert.equal(
      saved.reviewComment,
      trickyComment,
      "JSON-looking strings must be preserved verbatim, not parsed",
    );
    assert.equal(typeof saved.reviewComment, "string", "reviewComment must stay a string");
  }

  // ── 3. bulkUpdateReviewStatus passes through extraFields ─────────────────
  // The existing bulk path forwards an `extraFields` object through to
  // the same UPDATE statement. A future "reject with comment" UI would
  // use this — pin the contract now so a refactor of bulkUpdateReviewStatus
  // can't silently drop the field.
  {
    const project = makeProject();
    const id1 = makeTest(project.id);
    const id2 = makeTest(project.id);
    const reviewComment = "Rejected during bulk review — needs better assertions";

    const updated = testRepo.bulkUpdateReviewStatus(
      [id1, id2],
      project.id,
      "rejected",
      new Date().toISOString(),
      { reviewComment },
    );

    assert.equal(updated.length, 2, "both tests should be updated");
    for (const id of [id1, id2]) {
      const saved = testRepo.getById(id);
      assert.equal(saved.reviewStatus, "rejected");
      assert.equal(
        saved.reviewComment,
        reviewComment,
        "bulkUpdateReviewStatus must persist extraFields.reviewComment",
      );
    }
  }

  // ── 4. NULL by default + preserved across unrelated updates ──────────────
  // Pre-migration rows have `reviewComment = NULL`. Updating any OTHER
  // field (reviewStatus, qualityScore) must not blow away a previously-
  // set comment — the feedback loop sets the comment alongside many
  // other fields in one UPDATE, so accidental clearing would silently
  // hide the regeneration reason from users.
  {
    const project = makeProject();
    const testId = makeTest(project.id);

    // Fresh row defaults to NULL
    const fresh = testRepo.getById(testId);
    assert.equal(fresh.reviewComment, null, "fresh test should have NULL reviewComment");

    // Set it
    testRepo.update(testId, { reviewComment: "Original comment" });
    assert.equal(testRepo.getById(testId).reviewComment, "Original comment");

    // Touch an unrelated field — comment must survive
    testRepo.update(testId, { reviewStatus: "approved" });
    const afterStatusChange = testRepo.getById(testId);
    assert.equal(afterStatusChange.reviewStatus, "approved");
    assert.equal(
      afterStatusChange.reviewComment,
      "Original comment",
      "updating reviewStatus alone must NOT clear reviewComment",
    );
  }

  // ── 5. Explicit clear (null) writes through ──────────────────────────────
  // Restore / revoke flows clear approval provenance — they should also
  // be able to clear the review comment so a re-approved test doesn't
  // keep stale "Auto-regenerated after SELECTOR_ISSUE" copy that no
  // longer applies. The repo must distinguish "field omitted" from
  // "field explicitly null".
  {
    const project = makeProject();
    const testId = makeTest(project.id);

    testRepo.update(testId, { reviewComment: "Will be cleared" });
    assert.equal(testRepo.getById(testId).reviewComment, "Will be cleared");

    testRepo.update(testId, { reviewComment: null });
    assert.equal(
      testRepo.getById(testId).reviewComment,
      null,
      "explicit null must clear the column",
    );
  }

  console.log("✅ test-review-comment passed");
}

main().catch((err) => {
  console.error("❌ test-review-comment failed:", err);
  process.exit(1);
});
