-- DEPRECATED: This migration was renumbered to 005_notification_settings.sql
-- to resolve a numbering collision with 004_workspaces_rbac.sql.
--
-- This file is kept as a no-op so existing databases that already recorded
-- "004_notification_settings" in schema_migrations do not see a checksum
-- change warning.  New databases will apply 005_notification_settings.sql
-- instead (which is fully idempotent).
--
-- See 005_notification_settings.sql for the active migration.
