ALTER TABLE projects ADD COLUMN visionHealing TEXT NOT NULL DEFAULT 'off';
ALTER TABLE projects ADD COLUMN visionHealMaxCallsPerDay INTEGER NOT NULL DEFAULT 100;
ALTER TABLE projects ADD COLUMN visionHealMaxCostUsdPerMonth REAL NOT NULL DEFAULT 50;
