apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentri-postgres
spec:
  serviceName: sentri-postgres
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: sentri-secrets, key: POSTGRES_USER }
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef: { name: sentri-secrets, key: POSTGRES_DB }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: sentri-secrets, key: POSTGRES_PASSWORD }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: {{ .Values.postgres.storage }} } }
