apiVersion: v1
kind: Secret
metadata:
  name: sentri-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | default "sentri" | quote }}
